if 'encode' not in globals() or 'decode' not in globals():
    raise Exception("encode/decode function is not defined")

Tests.equal_check("encode empty string", "", encode(""))
Tests.equal_check("encode single characters only are encoded without count", "XYZ", encode("XYZ"))
Tests.equal_check("encode string with no single characters", "2A3B4C", encode("AABBBCCCC"))
Tests.equal_check("encode single characters mixed with repeated characters", "12WB12W3B24WB", encode("WWWWWWWWWWWWBWWWWWWWWWWWWBBBWWWWWWWWWWWWWWWWWWWWWWWWB"))
Tests.equal_check("encode multiple whitespace mixed in string", "2 hs2q q2w2 ", encode("  hsqq qww  "))
Tests.equal_check("encode lowercase characters", "2a3b4c", encode("aabbbcccc"))
Tests.equal_check("decode empty string", "", decode(""))
Tests.equal_check("decode single characters only", "XYZ", decode("XYZ"))
Tests.equal_check("decode string with no single characters", "AABBBCCCC", decode("2A3B4C"))
Tests.equal_check("decode single characters with repeated characters", "WWWWWWWWWWWWBWWWWWWWWWWWWBBBWWWWWWWWWWWWWWWWWWWWWWWWB", decode("12WB12W3B24WB"))
Tests.equal_check("decode multiple whitespace mixed in string", "  hsqq qww  ", decode("2 hs2q q2w2 "))
Tests.equal_check("decode lowercase string", "aabbbcccc", decode("2a3b4c"))
Tests.equal_check("encode followed by decode gives original string", "zzz ZZ  zZ", decode(encode("zzz ZZ  zZ")))
