export const settingsElements = {
    settings: {
        modal: document.getElementById('settings-modal') as HTMLElement,
        closeBtn: document.getElementById('close-settings-btn') as HTMLButtonElement,
        vimToggle: document.getElementById('vim-mode-toggle') as HTMLInputElement,
        chatToggle: document.getElementById('chat-mode-toggle') as HTMLInputElement,
        chatFields: document.getElementById('chat-settings-fields') as HTMLElement,
        endpointSection: document.getElementById('chat-endpoint-section') as HTMLElement,
        refreshModelsBtn: document.getElementById('refresh-models-btn') as HTMLButtonElement,
        chatModelContainer: document.getElementById('chat-model-container') as HTMLElement,
        // Gist Sync
        gistSyncBadge: document.getElementById('gist-sync-badge') as HTMLElement,
        gistSyncDot: document.getElementById('gist-sync-dot') as HTMLElement,
        gistSyncBadgeText: document.getElementById('gist-sync-badge-text') as HTMLElement,
        gistTokenContainer: document.getElementById('gist-token-container') as HTMLElement,
        gistGenerateTokenLink: document.getElementById('gist-generate-token-link') as HTMLAnchorElement,
        gistConfigFields: document.getElementById('gist-config-fields') as HTMLElement,
        gistIdInput: document.getElementById('gist-id-input') as HTMLInputElement,
        gistOpenLink: document.getElementById('gist-open-link') as HTMLAnchorElement,
        gistCreateBtn: document.getElementById('gist-create-btn') as HTMLButtonElement,
        gistCreateIcon: document.getElementById('gist-create-icon') as HTMLElement,
        gistLinkBtn: document.getElementById('gist-link-btn') as HTMLButtonElement,
        gistLinkIcon: document.getElementById('gist-link-icon') as HTMLElement,
        gistSyncNowBtn: document.getElementById('gist-sync-now-btn') as HTMLButtonElement,
        gistSyncNowIcon: document.getElementById('gist-sync-now-icon') as HTMLElement,
        gistSyncNowText: document.getElementById('gist-sync-now-text') as HTMLElement,
        gistPullBtn: document.getElementById('gist-pull-btn') as HTMLButtonElement,
        gistPullIcon: document.getElementById('gist-pull-icon') as HTMLElement,
        gistUnlinkBtn: document.getElementById('gist-unlink-btn') as HTMLButtonElement,
        gistAutosyncWrapper: document.getElementById('gist-autosync-wrapper') as HTMLElement,
        gistAutosyncToggle: document.getElementById('gist-autosync-toggle') as HTMLInputElement,
        gistStatusMsg: document.getElementById('gist-status-msg') as HTMLElement,

        exportBackupBtn: document.getElementById('export-backup-btn') as HTMLButtonElement,
        exportBackupIcon: document.getElementById('export-backup-icon') as HTMLElement,
        importBackupBtn: document.getElementById('import-backup-btn') as HTMLButtonElement,
        importBackupIcon: document.getElementById('import-backup-icon') as HTMLElement,
        importBackupInput: document.getElementById('import-backup-input') as HTMLInputElement,
        includeKeysCheckbox: document.getElementById('backup-include-keys') as HTMLInputElement,
        backupStatusMsg: document.getElementById('backup-status-msg') as HTMLElement,
        storageUsageDisplay: document.getElementById('storage-usage-display') as HTMLElement,
        clearStorageBtn: document.getElementById('clear-storage-btn') as HTMLButtonElement,
        clearStorageIcon: document.getElementById('clear-storage-icon') as HTMLElement,
    },
};
