export const settingsElements = {
    settings: {
        modal: document.getElementById('settings-modal') as HTMLElement,
        closeBtn: document.getElementById('close-settings-btn') as HTMLButtonElement,
        vimToggle: document.getElementById('vim-mode-toggle') as HTMLInputElement,
        chatToggle: document.getElementById('chat-mode-toggle') as HTMLInputElement,
        chatFields: document.getElementById('chat-settings-fields') as HTMLElement,
        endpointSection: document.getElementById('chat-endpoint-section') as HTMLElement,
        refreshModelsBtn: document.getElementById('refresh-models-btn') as HTMLButtonElement,
        chatModelContainer: document.getElementById('chat-model-container') as HTMLElement,
        // Gist Sync
        gistSyncBadge: document.getElementById('gist-sync-badge') as HTMLElement,
        gistSyncDot: document.getElementById('gist-sync-dot') as HTMLElement,
        gistSyncBadgeText: document.getElementById('gist-sync-badge-text') as HTMLElement,
        gistLoggedOutView: document.getElementById('gist-logged-out-view') as HTMLElement,
        gistLoggedInView: document.getElementById('gist-logged-in-view') as HTMLElement,
        gistOAuthLoginBtn: document.getElementById('gist-oauth-login-btn') as HTMLButtonElement,
        gistAccountUsername: document.getElementById('gist-account-username') as HTMLElement,
        gistOpenLink: document.getElementById('gist-open-link') as HTMLAnchorElement,
        gistSyncNowBtn: document.getElementById('gist-sync-now-btn') as HTMLButtonElement,
        gistSyncNowText: document.getElementById('gist-sync-now-text') as HTMLElement,
        gistPullBtn: document.getElementById('gist-pull-btn') as HTMLButtonElement,
        gistUnlinkBtn: document.getElementById('gist-unlink-btn') as HTMLButtonElement,
        gistAutosyncWrapper: document.getElementById('gist-autosync-wrapper') as HTMLElement,
        gistAutosyncToggle: document.getElementById('gist-autosync-toggle') as HTMLInputElement,
        gistStatusMsg: document.getElementById('gist-status-msg') as HTMLElement,
        gistManualToggleBtn: document.getElementById('gist-manual-toggle-btn') as HTMLButtonElement,
        gistManualChevron: document.getElementById('gist-manual-chevron') as HTMLElement,
        gistManualToggleLabel: document.getElementById('gist-manual-toggle-label') as HTMLElement,
        gistManualView: document.getElementById('gist-manual-view') as HTMLElement,
        gistManualToken: document.getElementById('gist-manual-token') as HTMLInputElement,
        gistManualId: document.getElementById('gist-manual-id') as HTMLInputElement,
        gistManualConnectBtn: document.getElementById('gist-manual-connect-btn') as HTMLButtonElement,

        exportBackupBtn: document.getElementById('export-backup-btn') as HTMLButtonElement,
        exportBackupIcon: document.getElementById('export-backup-icon') as HTMLElement,
        importBackupBtn: document.getElementById('import-backup-btn') as HTMLButtonElement,
        importBackupIcon: document.getElementById('import-backup-icon') as HTMLElement,
        importBackupInput: document.getElementById('import-backup-input') as HTMLInputElement,
        includeKeysCheckbox: document.getElementById('backup-include-keys') as HTMLInputElement,
        backupStatusMsg: document.getElementById('backup-status-msg') as HTMLElement,
        storageUsageDisplay: document.getElementById('storage-usage-display') as HTMLElement,
        clearStorageBtn: document.getElementById('clear-storage-btn') as HTMLButtonElement,
        clearStorageIcon: document.getElementById('clear-storage-icon') as HTMLElement,
    },
};
