import { byId } from './helpers';

export const settingsElements = {
    settings: {
        get modal() { return byId('settings-modal'); },
        get closeBtn() { return byId<HTMLButtonElement>('close-settings-btn'); },
        get vimToggle() { return byId<HTMLInputElement>('vim-mode-toggle'); },
        get chatToggle() { return byId<HTMLInputElement>('chat-mode-toggle'); },
        get chatFields() { return byId('chat-settings-fields'); },
        get endpointSection() { return byId('chat-endpoint-section'); },
        get refreshModelsBtn() { return byId<HTMLButtonElement>('refresh-models-btn'); },
        get chatModelContainer() { return byId('chat-model-container'); },
        // Gist Sync
        get gistSyncBadge() { return byId('gist-sync-badge'); },
        get gistSyncDot() { return byId('gist-sync-dot'); },
        get gistSyncBadgeText() { return byId('gist-sync-badge-text'); },
        get gistLoggedOutView() { return byId('gist-logged-out-view'); },
        get gistLoggedInView() { return byId('gist-logged-in-view'); },
        get gistOAuthLoginBtn() { return byId<HTMLButtonElement>('gist-oauth-login-btn'); },
        get gistAccountUsername() { return byId('gist-account-username'); },
        get gistOpenLink() { return byId<HTMLAnchorElement>('gist-open-link'); },
        get gistSyncNowBtn() { return byId<HTMLButtonElement>('gist-sync-now-btn'); },
        get gistSyncNowText() { return byId('gist-sync-now-text'); },
        get gistPullBtn() { return byId<HTMLButtonElement>('gist-pull-btn'); },
        get gistUnlinkBtn() { return byId<HTMLButtonElement>('gist-unlink-btn'); },
        get gistAutosyncWrapper() { return byId('gist-autosync-wrapper'); },
        get gistAutosyncToggle() { return byId<HTMLInputElement>('gist-autosync-toggle'); },
        get gistStatusMsg() { return byId('gist-status-msg'); },
        get gistManualToggleBtn() { return byId<HTMLButtonElement>('gist-manual-toggle-btn'); },
        get gistManualChevron() { return byId('gist-manual-chevron'); },
        get gistManualToggleLabel() { return byId('gist-manual-toggle-label'); },
        get gistManualView() { return byId('gist-manual-view'); },
        get gistManualToken() { return byId<HTMLInputElement>('gist-manual-token'); },
        get gistManualId() { return byId<HTMLInputElement>('gist-manual-id'); },
        get gistManualConnectBtn() { return byId<HTMLButtonElement>('gist-manual-connect-btn'); },

        get exportBackupBtn() { return byId<HTMLButtonElement>('export-backup-btn'); },
        get exportBackupIcon() { return byId('export-backup-icon'); },
        get importBackupBtn() { return byId<HTMLButtonElement>('import-backup-btn'); },
        get importBackupIcon() { return byId('import-backup-icon'); },
        get importBackupInput() { return byId<HTMLInputElement>('import-backup-input'); },
        get includeKeysCheckbox() { return byId<HTMLInputElement>('backup-include-keys'); },
        get backupStatusMsg() { return byId('backup-status-msg'); },
        get storageUsageDisplay() { return byId('storage-usage-display'); },
        get clearStorageBtn() { return byId<HTMLButtonElement>('clear-storage-btn'); },
        get clearStorageIcon() { return byId('clear-storage-icon'); },
    },
};

