export const speedrunElements = {
    speedrun: {
        modal: document.getElementById('speedrun-modal') as HTMLElement,
        closeBtn: document.getElementById('close-speedrun-btn') as HTMLButtonElement,
        headerIcon: document.getElementById('speedrun-header-icon') as HTMLElement,
        langSelect: document.getElementById('speedrun-lang-select') as HTMLSelectElement,
        startBtn: document.getElementById('speedrun-start-btn') as HTMLButtonElement,
        startBtnText: document.getElementById('speedrun-start-btn-text') as HTMLElement,
        exportBtn: document.getElementById('speedrun-export-btn') as HTMLButtonElement,
        exportIcon: document.getElementById('speedrun-export-icon') as HTMLElement,
        exportText: document.getElementById('speedrun-export-text') as HTMLElement,
        progressContainer: document.getElementById('speedrun-progress-container') as HTMLElement,
        progressBar: document.getElementById('speedrun-progress-bar') as HTMLElement,
        progressStatus: document.getElementById('speedrun-progress-status') as HTMLElement,
        progressCounter: document.getElementById('speedrun-progress-counter') as HTMLElement,
        statusFilters: document.getElementById('speedrun-status-filters') as HTMLElement,
        stats: {
            all: document.getElementById('stat-all') as HTMLElement,
            passed: document.getElementById('stat-passed') as HTMLElement,
            failed: document.getElementById('stat-failed') as HTMLElement,
            errors: document.getElementById('stat-errors') as HTMLElement,
            missing: document.getElementById('stat-missing') as HTMLElement,
            time: document.getElementById('stat-time') as HTMLElement,
        },
        sortBtn: document.getElementById('speedrun-sort-btn') as HTMLButtonElement,
        sortIcon: document.getElementById('speedrun-sort-icon') as HTMLElement,
        sortLabel: document.getElementById('speedrun-sort-label') as HTMLElement,
        resultsList: document.getElementById('speedrun-results-list') as HTMLElement,
    },
};
