if 'score' not in globals():
    raise Exception("score function is not defined")

Tests.equal_check("Yacht", 50, score([5, 5, 5, 5, 5], "yacht"))
Tests.equal_check("Not Yacht", 0, score([1, 3, 3, 2, 5], "yacht"))
Tests.equal_check("Ones", 3, score([1, 1, 1, 3, 5], "ones"))
Tests.equal_check("Ones out of order", 3, score([3, 1, 1, 5, 1], "ones"))
Tests.equal_check("No ones", 0, score([4, 3, 6, 5, 5], "ones"))
Tests.equal_check("Twos", 10, score([2, 3, 4, 5, 6], "twos"))
Tests.equal_check("Four of a Kind", 12, score([3, 3, 3, 3, 5], "four of a kind"))
Tests.equal_check("Four of a Kind from Yacht", 12, score([3, 3, 3, 3, 3], "four of a kind"))
Tests.equal_check("Full House", 19, score([3, 3, 3, 5, 5], "full house"))
Tests.equal_check("Full House not matching", 0, score([3, 3, 3, 3, 5], "full house"))
Tests.equal_check("Little Straight", 30, score([3, 5, 4, 1, 2], "little straight"))
Tests.equal_check("Big Straight", 30, score([4, 6, 2, 5, 3], "big straight"))
Tests.equal_check("Choice", 23, score([3, 3, 5, 6, 6], "choice"))
